### PR TITLE
RGB and other pixel types support 

### PR DESCRIPTION
**Pull request by bramalingam**
@dpwrussell : Have added support for rgb support,
Tested on a 8 bit rgb image, which did not have multiple channels (locally). And it worked. Happy to push changes if I've missed something.

### CODE REVIEW

**Review by jmuhlich — CHANGES_REQUESTED** [review]
I'm pretty sure RGB images should be imported as the actual three separate channels. For example, in H&E-stained histology slides the color information is critical. Can you explain more about why you need to convert to grayscale?

Furthermore the conversion math is wrong in a few ways, but let's resolve the above issue before getting to that.

**Comment by bramalingam** [comment]
@jmuhlich: I had a brief discussion with douglas, and we had decided that the gray scale conversion would be a simple workaround for the time being but I totally agree that treating them as the individual channels might be long term solution. For the deployment that we were testing locally, we had 16bit tiff's (rgb) and this workaround was all that was required. 

And regarding the conversion, 
I see some issues with the nested iterations (will push a fix), could you please elaborate on the other issues (if any)?

**Comment by jmuhlich** [comment]
OK then we just need to wrap the reader in the `ChannelSeparator` and leave it at that. It can be done even for non-RGB images as the ChannelSeparator acts as a pass-through in that case. The grayscale conversion can be deleted entirely.

The other issues (which are moot when the grayscale conversion is dropped) are: 1) photometric RGB images are usually gamma encoded and not linear intensity values, which means you need to perform an inverse gamma correction first. 2) For summing linear RGB to luminance you need to use the weighting factors `[0.2125, 0.7154, 0.0721]` instead of the ones you used. Your factors are the ones used to convert _gamma-encoded_ RGB pixels to a particular quantity called "luma" (_not_ the same thing as "luminance") which is called for in certain video encoding standards.

**Comment by bramalingam** [comment]
@jmuhlich : Thank you for the explanations, I have taken your suggestions and have looked into https://github.com/CellProfiler/python-bioformats/blob/master/bioformats/formatreader.py#L843, to fix the issue accordingly. It would be great if you take a look at this pr again.

**Comment by jmuhlich** [comment]
I think there is a much simpler way to achieve the goal here. I've gone ahead and implemented something in #11. We've tested it ourselves and it looks good, so we merged it to master. Try it out for yourself and see if it meets your needs.

**Pull request closed without merging**
